local map = vim.keymap.set
map({ "n", "v" }, "<leader>y", '"+y<CR>')
map({ "n", "v" }, "<leader>Y", '"+Y<CR>')
map("n", "<leader>sp", "<cmd>Telescope luasnip<CR>", { noremap = true, silent = true })
map("n", "Q", "<nop>")
map("n", "Q", ":bd<CR>", { noremap = true, silent = true })
map("n", "<leader>q", ":quit<CR>", { noremap = true, silent = true })
map("n", "<leader>w", ":write<CR>", { noremap = true, silent = true })
map("n", "<leader>bd", ":bd<CR>", { noremap = true, silent = true })
map("n", "<leader>o", "<cmd>DBUIToggle<CR>", { noremap = true, silent = true })
map("n", "<leader>t", ":tabnew<CR>", { noremap = true, silent = true })
map("n", "<leader>l", "gt", { noremap = true, silent = true })
map("n", "<leader>L", ':execute "tabmove" tabpagenr() + 1<CR>', { noremap = true, silent = true })
map("n", "<leader>h", "gT", { noremap = true, silent = true })
map("n", "<leader>H", ':execute "tabmove" tabpagenr() - 2 <CR>', { noremap = true, silent = true })
map({ "n", "v" }, "<leader>d", [["_d]])
map("n", "<leader>fm", vim.lsp.buf.format)
map("n", "<leader>j", "<cmd>cnext<CR>zz")
map("n", "<leader>k", "<cmd>cprev<CR>zz")
map("n", "<leader>gs", ":G<CR>")
map("n", "<leader>gb", ":Git blame<CR>")
map("n", "<leader>gvs", ":Gvdiffsplit<CR>")
map("n", "<leader>gvm", ":Gvdiffsplit master...:%<CR>")
map("n", "<leader>c", "<cmd>nohlsearch<CR>", { noremap = true, silent = true })
map("n", "<C-n>", ":NvimTreeToggle<CR>", { noremap = true, silent = true })
map("n", "<C-f>", ":NvimTreeFindFile<CR>", { noremap = true, silent = true })
map("n", "K", vim.lsp.buf.hover)
map("n", "<leader>i", vim.lsp.buf.code_action)
map("n", "<leader>ci", "<cmd>lua vim.lsp.buf.hover()<CR>", { noremap = true, silent = true })
map("n", "<leader>vrn", "<cmd>lua vim.lsp.buf.rename()<CR>", { noremap = true, silent = true })
map("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", { noremap = true, silent = true })
map("n", "[d", "<cmd>lua vim.diagnostic.goto_prev()<CR>", { noremap = true, silent = true })
map("n", "]d", "<cmd>lua vim.diagnostic.goto_next()<CR>", { noremap = true, silent = true })
map("n", "<leader>e", "<cmd>lua vim.diagnostic.open_float()<CR>", { noremap = true, silent = true })
map("n", "<leader>vd", "<cmd>lua vim.diagnostic.enable(not vim.diagnostic.is_enabled())<CR>", { noremap = true, silent = true })
map("n", "<leader>vf", "<cmd>lua vim.diagnostic.setloclist()<CR>", { noremap = true, silent = true })
map("n", "<leader>vq", "<cmd>lua vim.diagnostic.setqflist()<CR>", { noremap = true, silent = true })
map("n", "]c", "]czz", { noremap = true, silent = true })
map("n", "[c", "[czz", { noremap = true, silent = true })
map('n', 'gt', '<C-]>', { desc = 'Go to Tag (definition)' })
