vim.g.mapleader = " "
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.omni_sql_no_default_maps = 1
vim.g.db_ui_execute_on_save = 0
vim.g.db_ui_save_location = "~/db_ui"
vim.g.db_ui_tmp_query_location = '~/db_ui/queries'
vim.g.go_def_mapping_enabled = 0
vim.g.tmux_navigator_disable_when_zoomed = 1

vim.o.relativenumber = true
vim.o.number = true
vim.o.wrap = false
vim.o.termguicolors = true
vim.o.errorbells = false
vim.o.title = true
vim.o.autoindent = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.fixendofline = false
vim.o.lazyredraw = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.guicursor = "n-v-c:block,i:hor10"
vim.o.scrolloff = 5
vim.o.winborder = "rounded"
vim.o.signcolumn = "yes"
vim.o.completeopt = "menuone,noselect"
vim.o.swapfile = false
vim.o.laststatus = 0
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
